spring:
  application:
    name: o2-metadata
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.o2dev.org:3306/o2_metadata?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8}
    username: ${SPRING_DATASOURCE_USERNAME:o2Dev}
    password: ${SPRING_DATASOURCE_PASSWORD:o2Dev}
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:10}
      # 连接池允许的最大连接数
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:90}
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
  shardingsphere:
    datasource:
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.o2dev.org:3306/o2_metadata?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8}
        username: ${SPRING_DATASOURCE_USERNAME:o2Dev}
        password: ${SPRING_DATASOURCE_PASSWORD:o2Dev}
      slave0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: ${SPRING_DATASOURCE_SLAVE_URL:jdbc:mysql://db.o2dev.org:3306/o2_metadata?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8}
        username: ${SPRING_DATASOURCE_USERNAME:o2Dev}
        password: ${SPRING_DATASOURCE_PASSWORD:o2Dev}
      names: master,slave0
    masterslave:
      name: o2
      master-data-source-name: master
      slave-data-source-names: slave0
    props:
      sql:
        show: true

  redis:
    host: ${REDIS_DEFAULT_URL:redis.hzero.org}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:}
    database: ${SPRING_REDIS_DATABASE:1}
    jedis:
      pool:
        # 资源池中最大连接数
        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整
        max-active: ${SPRING_REDIS_POOL_MAX_ACTIVE:16}
        # 资源池运行最大空闲的连接数
        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整，一般建议和max-active保持一致，避免资源伸缩带来的开销
        max-idle: ${SPRING_REDIS_POOL_MAX_IDLE:16}
        # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
        # 默认 -1 表示永不超时，设置5秒
        max-wait: ${SPRING_REDIS_POOL_MAX_WAIT:5000}
  data:
    mongodb:
      uri: ${MONGODB_DEFAULT_URL:mongodb://root:root@mongo-0:27017/admin}

mybatis:
  configuration:
    # 数据库下划线转驼峰配置
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml

o2:
  redis:
    cache:
      host: ${O2_REDIS_HOST:192.168.12.237}
      port: ${O2_REDIS_PORT:6379}
      password: ${O2_REDIS_PASSWORD:1q2w3e4r5t}
      timeout-millis: ${O2_REDIS_COMMAND_TIMEOUT_MILLIS:3000}
      pool-min-idle: ${O2_REDIS_POOL_MIN_IDLE:4}
      pool-max-idle: ${O2_REDIS_POOL_MAX_IDLE:8}
      pool-max-wait-millis: ${O2_REDIS_POOL_MAX_WAIT_MILLIS:30000}

hzero:
  lov:
    sql:
      enabled: ${HZERO_LOV_SQL_ENABLED:true}
    value:
      enabled: ${HZERO_LOV_VALUE_ENABLED:true}
  data:
    permission:
      db-owner: ${HZERO_DB_OWNER:}

logging:
  level:
    org.apache.ibatis: ${LOG_LEVEL:debug}
    io.choerodon: ${LOG_LEVEL:debug}
    org.hzero.platform.infra.mapper: ${LOG_LEVEL:debug}