image: registry.cn-shanghai.aliyuncs.com/c7n/cibase:0.11.0

stages:
  - sonar
  - maven_deploy

sonar_check:
  stage: sonar
  script:
    - mvn --batch-mode clean verify sonar:sonar
      -Dsonar.host.url=${O2_SONAR_URL}
      -Dsonar.login=${SONAR_TOKEN}
      -Dsonar.sourceEncoding=UTF-8
      -Dsonar.gitlab.project_id=${CI_PROJECT_ID}
      -Dsonar.branch.name=${CI_COMMIT_REF_NAME}
      -Dsonar.projectKey=${SONAR_PROJECT_KEY}
      -Dsonar.projectVersion=${CI_COMMIT_TAG}
      -Dsonar.java.binaries=target/classes
      -Dmaven.test.failure.ignore=true
      -DskipTests=true
  allow_failure: true
  only:
    - sonar
    - master

maven_deploy:
  stage: maven_deploy
  script:
    - mvn clean -U -Dmaven.test.skip=true -Dspring-boot.repackage.skip=true -Dfile.encoding=UTF-8 deploy
  only:
    - dev
    - master
    - prod


before_script:
  - |
    http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
    if [ "$http_status_code" != "200" ]; then
      cat ./.auto_devops.sh
      exit 1
    fi
    source ./.auto_devops.sh
