image: registry.cn-shanghai.aliyuncs.com/c7n/cibase:0.11.0

stages:
  - sonar
  - maven_package

sonar_check:
  stage: sonar
  script:
    - mvn --batch-mode clean verify sonar:sonar
      -Dsonar.host.url=${O2_SONAR_URL}
      -Dsonar.login=${SONAR_TOKEN}
      -Dsonar.sorceEncoding=UTF-8
      -Dsonar.projectKey=${SONAR_PROJECT_KEY}
      -Dmaven.test.failure.ignore=true
      -DskipTests=true
  only:
    - sonar
    - master

maven_package:
  stage: maven_package
  script:
    - mvn clean -U -Dmaven.test.skip=true -Dspring-boot.repackage.skip=true -Dfile.encoding=UTF-8 deploy
  only:
    - dev
    - master
    - prod
    - test
    - /^*-SNAPSHOT$/

before_script:
  - |
    http_status_code=`curl -o .auto_devops.sh -s -m 10 --connect-timeout 10 -w %{http_code} "${CHOERODON_URL}/devops/ci?token=${Token}&type=microservice"`
    if [ "$http_status_code" != "200" ]; then
      cat ./.auto_devops.sh
      exit 1
    fi
    source ./.auto_devops.sh
