spring:
  application:
    name: o2-metadata-console
    hone-route:
      name: o2md-c
      path: /o2md-c/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.o2dev.org:3306/o2_metadata?useUnicode=true&characterEncoding=utf-8&useSSL=false&useTimezone=true&serverTimezone=GMT%2B8}
    username: ${SPRING_DATASOURCE_USERNAME:o2Dev}
    password: ${SPRING_DATASOURCE_PASSWORD:o2Dev}
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:10}
      # 连接池允许的最大连接数
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:90}
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
  redis:
    host: ${REDIS_DEFAULT_URL:redis.hzero.org}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${SPRING_REDIS_PASSWORD:}
    database: ${SPRING_REDIS_DATABASE:1}
    jedis:
      pool:
        # 资源池中最大连接数
        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整
        max-active: ${SPRING_REDIS_POOL_MAX_ACTIVE:16}
        # 资源池运行最大空闲的连接数
        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整，一般建议和max-active保持一致，避免资源伸缩带来的开销
        max-idle: ${SPRING_REDIS_POOL_MAX_IDLE:16}
        # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
        # 默认 -1 表示永不超时，设置5秒
        max-wait: ${SPRING_REDIS_POOL_MAX_WAIT:5000}

server:
  port: 9102
  undertow:
    # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接
    # 默认值为8，建议设置每个CPU核心一个线程
    io-threads: ${SERVER_UNDERTOW_IO_THREADS:4}
    # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程
    # 默认等于 io-threads*8，它的值设置取决于系统的负载，可适当调大该值
    worker-threads: ${SERVER_UNDERTOW_WORKER_THREADS:128}
    # 每块buffer的空间大小，越小空间被利用越充分
    # 不要设置太大，以免影响其他应用，合适即可
    buffer-size: ${SERVER_UNDERTOW_BUFFER_SIZE:1024}
    # 是否分配的直接内存(NIO直接分配的堆外内存)
    # 默认false
    direct-buffers: true
    # HTTP POST请求最大的大小
    # 默认0，无限制，可设置10M
    max-http-post-size: 10485760
management:
  server:
    port: 9103
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    # 数据库下划线转驼峰配置
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:/mapper/*.xml

o2:
  redis:
    cache:
      host: ${O2_REDIS_HOST:192.168.17.211}
      port: ${O2_REDIS_PORT:6379}
      password: ${O2_REDIS_PASSWORD:1q2w3e4r5t}
      timeout-millis: ${O2_REDIS_COMMAND_TIMEOUT_MILLIS:3000}
      pool-min-idle: ${O2_REDIS_POOL_MIN_IDLE:4}
      pool-max-idle: ${O2_REDIS_POOL_MAX_IDLE:8}
      pool-max-wait-millis: ${O2_REDIS_POOL_MAX_WAIT_MILLIS:30000}
  dubbo:
    registry:
      address: ${DUBBO_REDIS_REGISTRY_ADDRESS:redis://dubbo.redis.org:9379?db.index=3&min.idle=4&max.active=16&max.total=16}

hzero:
  lov:
    sql:
      enabled: ${HZERO_LOV_SQL_ENABLED:true}
    value:
      enabled: ${HZERO_LOV_VALUE_ENABLED:true}
  data:
    permission:
      db-owner: ${HZERO_DB_OWNER:}

logging:
  level:
    org.apache.ibatis: ${LOG_LEVEL:debug}
    io.choerodon: ${LOG_LEVEL:debug}
    org.hzero.platform.infra.mapper: ${LOG_LEVEL:debug}